import axios from "axios"
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import { useState, useEffect, use } from 'react'
import Pagination from "@/components/pagination"
import { paginate } from "./../utils/paginate";

const Home = () => {

  const [posts, setPosts] = useState([])
  const [currentPage, setCurrentPage] = useState(1)
  const pageSize = 10
  
  useEffect(() => {
    const getPosts = async () => {
      const { data: res } = await axios.get("https://jsonplaceholder.typicode.com/posts")
      setPosts(res)
    }
    getPosts()
  },[])

  const handlePageChange = (page) => {
    setCurrentPage(page)
  }

  const paginatePosts = paginate(posts, currentPage, pageSize);

  return (
    <>
      <Head>
        <title>Pagination App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="container">
          <table className="table">
              <thead className="thead-dark">
                <tr>
                  <th>Post</th>
                  <th>Date</th>
                </tr>
              </thead>
              <tbody>
                {paginatePosts.map(post =>
                  <tr key={post.id}>
                    <td>{post.title}</td>
                    <td>{post.id}/3/2023</td>
                  </tr>
                  )}
              </tbody>
            </table>
            <Pagination items={posts.length} currentPage={currentPage} pageSize={pageSize} onPageChange={handlePageChange} />
        </section>
      </main>
    </>
  )
}

export default Home;
